newssite/news/urls.py
from django.urls import path
from news.views import news, new_detail

app_name = 'news'

urlpatterns = [
    path('', news, name='index'),
    path('<int:new_id>/', new_detail, name='new_detail'),
    path('page/<int:page>/', news, name='page')
]

newssite/newssite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from news.views import index, author

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('new/', include('news.urls', namespace='news')),
    path('author/', author, name='author')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newssite/news/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class NewCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=64, verbose_name='Имя')
    last_name = models.CharField(max_length=64, verbose_name='Фамилия')
    description = models.TextField(blank=True, verbose_name='Описание')
    short_descr = models.CharField(max_length=100, blank=True, verbose_name='Краткое описание')
    is_published = models.BooleanField(default=True, verbose_name='Публикация')
    image = models.ImageField(upload_to='author_images', blank=True, verbose_name='Фотография')

    class Meta:
        verbose_name_plural = 'Авторы'
        ordering = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class New(models.Model):
    header = models.CharField(max_length=64, verbose_name='Заголовок')
    image = models.ImageField(upload_to='news_images', blank=True, verbose_name='Фотография')
    description = models.TextField(blank=True, verbose_name='Описание')
    short_descr = models.CharField(max_length=64, blank=True, verbose_name='Краткое описание')
    category = models.ForeignKey(NewCategory, on_delete=models.CASCADE, verbose_name='Категория')
    is_published = models.BooleanField(default=True, verbose_name='Публикация')
    author = models.ManyToManyField(Author, blank=True, verbose_name='Автор')

    class Meta:
        verbose_name_plural = 'Новости'
        ordering = ['id']

    def __str__(self):
        return f'{self.header} | {self.category.name}'

newssite/news/views.py
from django.shortcuts import render, get_object_or_404
from news.models import New, NewCategory, Author
from django.core.paginator import Paginator


# Create your views here.
def index(request):

    contex = {
        'title': 'Главная',
        'categories': NewCategory.objects.all(),
        'news': New.objects.all()
    }
    return render(request, 'news/index.html', contex)


def new_detail(request, new_id):
    new = get_object_or_404(New, pk=new_id)
    contex = {
        'title': 'All news',
        'author': author,
        'new': new,

    }
    return render(request, 'news/new_detail.html', contex)


def news(request, page=1):
    news = New.objects.all()
    contex = {
        'title': 'Новости',
        'categories': NewCategory.objects.all(),
        'news': news
    }
    paginator = Paginator(news, 9)
    news_paginator = paginator.page(page)
    contex.update({'news': news_paginator})
    return render(request, 'news/new.html', contex)


def author(request):
    contex = {
        'title': 'All Authors',
        'authors': Author.objects.all()
    }
    return render(request, 'news/author.html', contex)

newssite/news/templates/news/author.html
{% extends 'news/base.html' %}

{% block content %}
    <p>Для теста</p>
    {% for author in authors %}
        <div> {{ author.first_name }}</div>
        <div> <img src="/media/{{ author.image }}"></div>
    {% endfor %}
{% endblock %}

newssite/news/templates/news/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title|title }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <header>
        <div class="top">
            <div class="container">
                <div class="top-wrapper">
                    <div class="top-left">
                        <a href="{% url 'index' %}" class="top-logo">
                            <img src="{% static 'img/logo/logo-cnews.png' %}" alt="logo">
                        </a>
                        <div class="top-menu">
                            <ul class="top-menu_items">
                                <li>
                                    <a href="{% url 'news:index' %}">Новости</a>
                                </li>
                                <li>
                                    <a href="{% url 'author' %}">Аналитика</a>
                                </li>
                                <li>
                                    <a href="#">Конференции</a>
                                </li>
                                <li>
                                    <a href="#">Маркет</a>
                                </li>
                                <li>
                                    <a href="#">Техника</a>
                                </li>
                                <li>
                                    <a href="#">ТВ</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="top-right">
                        <a href="#">Вход |</a>
                        <a href="#"> Регистрация</a>
                    </div>
                </div>
            </div>
        </div>
        {% block header %}{% endblock %}
    </header>

    {% block content %}{% endblock %}
    {% block pagination %}
        <div class="pagination">
            <ul class="pagination-list justify-content-center">
                <li class="page-item {% if not news.has_previous %} disabled  {% endif %}">
                    <a class="page-link" href="{% if news.has_previous %} {% url 'news:page' news.previous_page_number %} {% else %} # {% endif %}">Previous</a>
                </li>
                {% for page in news.paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'news:page' page %}">{{ page }}</a>
                    </li>
                {% endfor %}
                <li class="page-item {% if not news.has_next %} disabled  {% endif %}">
                    <a class="page-link" href="{% if news.has_next %} {% url 'news:page' news.next_page_number %} {% else %} # {% endif %}">Next</a>
                </li>
            </ul>
        </div>
        {% endblock %}

 <footer class="footer">
        <div class="container">
            <div class="footer-wrapper">
                <div class="copy">
                    Все права защищены © 1995 - 2021 CNews
                </div>
                <div class="footer-cnews">
                    <a href="#">CNews</a>
                </div>
                <ul class="footer-menu">
                    <li>
                        <a href="#">Новости</a>
                    </li>
                    <li>
                        <a href="#">Аналитика</a>
                    </li>
                    <li>
                        <a href="#">Маркет</a>
                    </li>
                    <li>
                        <a href="#">ТВ</a>
                    </li>
                    <li>
                        <a href="#">Блоги</a>
                    </li>
                    <li>
                        <a href="#">Техника</a>
                    </li>
                    <li>
                        <a href="#">Наука</a>
                    </li>
                    <li>
                        <a href="#">Софт</a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

newssite/news/templates/news/index.html
{% extends 'news/base.html' %}
{% load static %}

{% block header %}
<div class="header">
            <div class="container">
                <div class="wrapper">
                    <div class="header-logo">
                        <a href="#">
                            <img src="{% static 'img/logo/logo_events.png' %}" alt="header-logo">
                        </a>
                    </div>
                    <div class="header-title">Агентство маркетинговых коммуникаций</div>
                    <div class="header-descr">CNews Conferences поможет организовать мероприятия, которые получат максимальный резонанс в бизнес-среде и привлекут к Вам новых партнеров и клиентов.</div>
                    <div class="header-detail">
                        <a href="#">подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        <nav class="menu">
            <div class="container">
                <ul class="menu-wrapper">
                    <li>
                        <a href="#">
                            <img src="{% static 'img/logo/logo-event.png' %}" alt="logo">
                        </a>
                    </li>
                    <li>
                        <a href="#">О компании</a>
                    </li>
                    <li>
                        <a href="#">Ближайшие мероприятия</a>
                    </li>
                    <li>
                        <a href="#">Материалы</a>
                    </li>
                    <li>
                        <a href="#">Архив мероприятий</a>
                    </li>
                    <li>
                        <a href="#">КОНТАКТЫ</a>
                    </li>
                </ul>
            </div>
        </nav>
{% endblock %}

{% block content %}
    <section class="news">
        <div class="container">
            <div class="news-content">
                {% for new in news %}
                    <div class="news-item">
                        <a href="{% url 'news:new_detail' new.id %}">
                            <div class="news-item_img">
                                <img src="/media/{{ new.image }}" alt="img">
                            </div>
                            <div class="news-item_header">{{ new.header }}</div>
                            <div class="news-item_category"> {{ new.category }}</div>
                            <div class="news-item_descr">{{ new.short_descr }}</div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock%}

newssite/news/templates/news/new.html
{% extends 'news/base.html' %}
{% load static %}
{% block content %}
    <section class="news">
        <div class="container">
            <div class="news-content">
                {% for new in news %}
                    {% if new.is_published %}
                        <div class="news-item">
                            <a href="{% url 'news:new_detail' new.id %}">
                                <div class="news-item_img">
                                    <img src="/media/{{ new.image }}" alt="img">
                                </div>
                                <div class="news-item_header">{{ new.header }}</div>
                                <div class="news-item_category"> {{ new.category }}</div>
                                <div class="news-item_descr">{{ new.short_descr }}</div>
                            </a>
                        </div>
                    {% endif  %}
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

newssite/news/templates/news/new_detail.html
{% extends 'news/base.html' %}

{% block content %}
    <div class="detail-new">
        <div class="container">
            <div class="detail-new_img">
                <img src=" /media/{{ new.image }}" alt="img">
            </div>
            <div class="detail-new_header">{{ new.header }}</div>
            <div class="detail-new_category">{{ new.category }}</div>
            <div class="detail-new_descr">{{ new.description }}</div>
            <h2 class="author-title">Авторы новости</h2>
            <div class="author-content">
                {% for author in new.author.all %}
                    <div class="author-list">
                         <div class="author-img">
                            <img src="/media/{{ author.image }}" alt="img">
                        </div>
                        <div class="author_name">{{ author.first_name }} {{ author.last_name }}</div>
                        <div class="author-short_descr">{{ author.short_descr }}</div>
                        <div class="author-last_description">{{ author.description }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% block pagination %}{% endblock %}
{% endblock %}